---
- name: Update Home Assistant via API
  hosts: localhost
  vars:
    ha_url: "https://192.168.86.212:8123"
    ha_token: "{{ HA_TOKEN }}"

  tasks:
    - name: Check current Home Assistant version
      uri:
        url: "{{ ha_url }}/api/config"
        method: GET
        headers:
          Authorization: "Bearer {{ ha_token }}"
          Content-Type: "application/json"
        status_code: 200
        validate_certs: no
      register: ha_config

    - name: Display current version
      debug:
        msg: "Current Home Assistant version: {{ ha_config.json.version }}"

    - name: Check for available updates using supervisor API
      uri:
        url: "{{ ha_url }}/api/hassio/update"
        method: GET
        headers:
          Authorization: "Bearer {{ ha_token }}"
          Content-Type: "application/json"
          # Supervisor might need this header:
          X-Hassio-Key: "{{ ha_token }}"
        status_code: 200
        validate_certs: no
      register: ha_updates
      ignore_errors: yes # ← Continue even if this fails

    - name: Alternative method - Check updates via core API
      uri:
        url: "{{ ha_url }}/api/hassio/core/info"
        method: GET
        headers:
          Authorization: "Bearer {{ ha_token }}"
          Content-Type: "application/json"
        status_code: 200
        validate_certs: no
      register: ha_core_info
      when: ha_updates is failed

    - name: Display update information
      debug:
        msg: |
          Update check results:
          - Core version: {{ ha_core_info.json.data.version | default('Unknown') }}
          - Latest version: {{ ha_core_info.json.data.version_latest | default('Unknown') }}
          - Update available: {{ (ha_core_info.json.data.version != ha_core_info.json.data.version_latest) | default(false) }}
      when: ha_core_info is defined

    - name: Update Home Assistant Core if needed
      uri:
        url: "{{ ha_url }}/api/hassio/core/update"
        method: POST
        headers:
          Authorization: "Bearer {{ ha_token }}"
          Content-Type: "application/json"
        status_code: 200
        validate_certs: no
      when:
        - ha_core_info is defined
        - ha_core_info.json.data.version != ha_core_info.json.data.version_latest
