---
- name: Update Proxmox Server
  hosts: proxmox_servers # This matches the group name in inventory
  become: yes
  gather_facts: yes

  tasks:
    - name: Check current Proxmox version
      command: pveversion
      register: pve_version
      changed_when: false

    - name: Display current Proxmox version
      debug:
        msg: "Current Proxmox version: {{ pve_version.stdout }}"

    - name: Update Proxmox packages
      apt:
        update_cache: yes
        upgrade: safe
        cache_valid_time: 3600

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify about reboot requirement
      debug:
        msg: "Reboot required to complete updates"
      when: reboot_required.stat.exists
